### ISSUE TITLE
Create Header and Footer as a component and design that as in the below screenshots

### ISSUE THREAD

**Issue by Bhanu-nd** [navadhiti/societalplatform-muse#13]
![image](https://user-images.githubusercontent.com/58928812/206977792-472926c2-302d-4519-8430-58959549afce.png)
![image](https://user-images.githubusercontent.com/58928812/206977849-f53ad80e-7c75-4af6-872c-d7a3fe12a1b4.png)

**Comment by rajesh-nd** [comment]
.
